In [2]:
import pandas as pd
import numpy as np
import nltk
import re      #regular expression

In [4]:
from nltk.corpus import stopwords

In [18]:
#sample dataset
# data={
#     "text":["Sanju Samson had the crowd on its feet. They were banging the seats, they were screaming their lungs out.",
#             "At a time when Bollywood keeps glorifying scarcity, delay and aura, Akshay Kumar stands out for a very different reason: he is useful. ",
#             "BBC Ruling Trinamool Congress leaders campaign with fish as a symbol of identity in Kolkata",
#             "GIFT NIFTY futures traded 71 points higher on Friday morning, indicating a positive start for the day.",
#             "Dear Donald Trump, here's how you end the war with Iran.",
#             "Thirteen killed in second India fireworks blast in three days.",
#             "Meta to layoff 8,000 from its workforce, amid AI spending push",],
#         "category":["Sports","Entertainment","Political News","Business"]}

df=pd.read_csv("train.csv")
df

        Id                                           Headline   Category
0        1           Breakthrough discovery in cyber research    Science
1        2   Government focuses on youth development programs    Society
2        3   health party wins majority in assembly elections   Politics
3        4  Startups in digital sector attract global inve...   Business
4        5  Sensex surges by technology points amid market...   Business
...    ...                                                ...        ...
4995  4996  Startups in women sector attract global investors   Business
4996  4997       CBSE implements space curriculum for schools  Education
4997  4998     India achieves milestone in finance technology    Science
4998  4999           India signs trade deal with river nation   Business
4999  5000       BCCI announces schedule for cyber tournament     Sports

[5000 rows x 3 columns]

In [19]:
# preprocessing

stop_words=set(stopwords.words('english'))

def preprocess(Headline):
    text=Headline.lower()   #convert text in lowercase
    words=text.split()   #tokenisation
    words=[word for word in words if word not in stop_words]
    return " ".join(words)

df['Cleaned']=df['Headline'].apply(preprocess)  #for storing text in another column
df

,Id,Headline,Category,Cleaned
0,1,Breakthrough discovery in cyber research,Science,breakthrough discovery cyber research
1,2,Government focuses on youth development programs,Society,government focuses youth development programs
2,3,health party wins majority in assembly elections,Politics,health party wins majority assembly elections
3,4,Startups in digital sector attract global inve...,Business,startups digital sector attract global investors
4,5,Sensex surges by technology points amid market...,Business,sensex surges technology points amid market op...
...,...,...,...,...
4995,4996,Startups in women sector attract global investors,Business,startups women sector attract global investors
4996,4997,CBSE implements space curriculum for schools,Education,cbse implements space curriculum schools
4997,4998,India achieves milestone in finance technology,Science,india achieves milestone finance technology
4998,4999,India signs trade deal with river nation,Business,india signs trade deal river nation
4999,5000,BCCI announces schedule for cyber tournament,Sports,bcci announces schedule cyber tournament

In [20]:
# split the dataset
from sklearn.model_selection import train_test_split

x=df['Cleaned']
y=df['Category']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
# feature selection (TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer= TfidfVectorizer()
x_train_v= vectorizer.fit_transform(x_train)
x_test_v= vectorizer.transform(x_test)

In [27]:
#train model
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_v,y_train)

MultinomialNB()

In [28]:
# model evaluation

from sklearn.metrics import accuracy_score

pred= model.predict(x_test_v)

print("Accuracy:",accuracy_score(y_test,pred))

Accuracy: 1.0

In [31]:
#test sample data

def pred_news(Headline):
    text_clean=preprocess(Headline)
    text_vec=vectorizer.transform([text_clean])
    prediction=model.predict(text_vec)
    return prediction[0]

In [36]:
print(pred_news("Trade setup for April 24: Can NIFTY50 bounce back above 50 EMA on Friday"))
print(pred_news("Recently, Kajol spoke about her character Simran from DDLJ and said that someone like her no longer exists in today's world."))
print(pred_news("EC issues fresh post-poll guidelines for Bengal assembly elections"))
print(pred_news("'Look for answers inside, not outside': Rishabh Pant tells his LSG team after fourth straight defeat."))

Business
Education
Politics
Sports