In [1]:
import numpy as np
import pandas as pd

In [2]:
n=1000

data={"income":np.random.randint(50000,200000,n),  
      "Age":np.random.randint(21,60,n),
      "LoanAmount":np.random.randint(10000,100000,n),
      "CreditScore":np.random.randint(300,900,n)
     }

In [3]:
df=pd.DataFrame(data)
df

     income  Age  LoanAmount  CreditScore
0     52930   25       23665          772
1    169425   26       99442          790
2    107993   45       62616          424
3    128986   46       47330          481
4    156985   54       82209          716
..      ...  ...         ...          ...
995   66301   31       82946          894
996  126625   28       59445          388
997   62324   24       29246          650
998   88595   49       62031          484
999   64253   35       35769          852

[1000 rows x 4 columns]

In [4]:
# rule-based target

df["Approved"]=(
    (df["income"]>50000)&
    (df["CreditScore"]>600)&
    (df["LoanAmount"]>50000)).astype(int)   # it converts boolean to integer

df

     income  Age  LoanAmount  CreditScore  Approved
0     52930   25       23665          772         0
1    169425   26       99442          790         1
2    107993   45       62616          424         0
3    128986   46       47330          481         0
4    156985   54       82209          716         1
..      ...  ...         ...          ...       ...
995   66301   31       82946          894         1
996  126625   28       59445          388         0
997   62324   24       29246          650         0
998   88595   49       62031          484         0
999   64253   35       35769          852         0

[1000 rows x 5 columns]

In [5]:
#split features
x=df.drop("Approved",axis=1)
y=df["Approved"]

In [6]:
# train test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
#scaling= convert range into same scale to predict model
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()

x_train=scale.fit_transform(x_train)    # it calculates the mean and SD of each features in training set
x_test=scale.transform(x_test)

In [10]:
#build a neural network
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input

model=Sequential([
    Input(shape=(x_train.shape[1],)),
    Dense(10,activation='relu'),
    Dense(8,activation='relu'),
    Dense(1,activation='sigmoid')])

In [12]:
# COMPILE
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [13]:
# train model
model.fit(x_train,y_train,epochs=20,batch_size=16,  validation_data=(x_test,y_test))

Epoch 1/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6875 - loss: 0.5942 - val_accuracy: 0.7250 - val_loss: 0.5510
Epoch 2/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5206 - val_accuracy: 0.7450 - val_loss: 0.4868
Epoch 3/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7462 - loss: 0.4617 - val_accuracy: 0.7900 - val_loss: 0.4314
Epoch 4/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7975 - loss: 0.4095 - val_accuracy: 0.8450 - val_loss: 0.3816
Epoch 5/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8450 - loss: 0.3604 - val_accuracy: 0.8550 - val_loss: 0.3387
Epoch 6/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8587 - loss: 0.3162 - val_accuracy: 0.8800 - val_loss: 0.2985
Epoch 7/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8825 - loss: 0.2762 - val_accuracy: 0.8900 - val_loss: 0.2622
Epoch 8/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9013 - loss: 0.2405 - val_accuracy: 0.9000 - val_loss: 0.2309
Epoch 9/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9212 - loss: 0.2089 - val_accuracy: 0.9200 - val_loss: 0.2014
Epoch 10/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9362 - loss: 0.1815 - val_accuracy: 0.9300 - val_loss: 0.1783
Epoch 11/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9475 - loss: 0.1586 - val_accuracy: 0.9500 - val_loss: 0.1569
Epoch 12/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9575 - loss: 0.1389 - val_accuracy: 0.9600 - val_loss: 0.1408
Epoch 13/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9625 - loss: 0.1224 - val_accuracy: 0.9550 - val_loss: 0.1268
Epoch 14/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9675 - loss: 0.1091 - val_accuracy: 0.9700 - val_loss: 0.1167
Epoch 15/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9712 - loss: 0.0981 - val_accuracy: 0.9650 - val_loss: 0.1065
Epoch 16/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9750 - loss: 0.0890 - val_accuracy: 0.9650 - val_loss: 0.0991
Epoch 17/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9787 - loss: 0.0815 - val_accuracy: 0.9750 - val_loss: 0.0922
Epoch 18/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9812 - loss: 0.0746 - val_accuracy: 0.9700 - val_loss: 0.0854
Epoch 19/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9812 - loss: 0.0700 - val_accuracy: 0.9700 - val_loss: 0.0801
Epoch 20/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9812 - loss: 0.0649 - val_accuracy: 0.9800 - val_loss: 0.0752

In [16]:
# evaluation
loss,accuracy=model.evaluate(x_test,y_test)
print("Accuracy:",accuracy)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9800 - loss: 0.0752
Accuracy: 0.9800000190734863

In [105]:
# test on new data
new_data=pd.DataFrame({
    "income":[750000],
    "Age":[30],
    "LoanAmount":[100000],
    "CreditScore":[750]})

In [106]:
new_data_scale=scale.transform(new_data)

In [107]:
predict=model.predict(new_data_scale)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step

In [108]:
final=(predict >0.5).astype(int)

print("Approval Probability :",predict[0][0])
print("Loan Approval Status :",final[0][0])

Approval Probability : 0.8997386
Loan Approval Status : 1